services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB_FILE:       /run/secrets/db_name
      POSTGRES_USER_FILE:     /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
      - db_user
      - db_name
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

secrets:
  db_password:
    file: ./db_password.txt
  db_user:
    file: ./db_user.txt
  db_name:
    file: ./db_name.txt

volumes:
  db_data:
