services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB:       integration_db
      POSTGRES_USER:     db_user
      POSTGRES_PASSWORD: integration
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data:
