# Generated by Django 5.2.1 on 2025-06-02 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', 'commodity-rename-migration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commodity',
            options={'verbose_name': 'Commodity', 'verbose_name_plural': 'Commodities'},
        ),
    ]
