from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('app', '0001_initial'),  
    ]

    operations = [
        migrations.RenameField(
            model_name='commodity',
            old_name='crude_oil_average',
            new_name='crude_oil_average_bbl',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='crude_oil_brent',
            new_name='crude_oil_brent_bbl',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='crude_oil_dubai',
            new_name='crude_oil_dubai_bbl',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='crude_oil_wti',
            new_name='crude_oil_wti_bbl',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='coal_australian',
            new_name='coal_australian_mt',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='coal_south_african',
            new_name='coal_south_african_mt',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='natural_gas_us',
            new_name='natural_gas_us_mmbtu',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='natural_gas_europe',
            new_name='natural_gas_europe_mmbtu',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='liquefied_natural_gas_japan',
            new_name='liquefied_natural_gas_japan_mmbtu',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='natural_gas_index',
            new_name='natural_gas_index_2010_100',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='coffee_arabica',
            new_name='coffee_arabica_kg',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='coffee_robusta',
            new_name='coffee_robusta_kg',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='tea_avg_3_auctions',
            new_name='tea_avg_3_auctions_kg',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='tea_colombo',
            new_name='tea_colombo_kg',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='tea_kolkata',
            new_name='tea_kolkata_kg',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='tea_mombasa',
            new_name='tea_mombasa_kg',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='coconut_oil',
            new_name='coconut_oil_mt',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='groundnuts',
            new_name='groundnuts_mt',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='fish_meal',
            new_name='fish_meal_mt',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='groundnut_oil',
            new_name='groundnut_oil_mt',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='palm_oil',
            new_name='palm_oil_mt',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='palm_kernel_oil',
            new_name='palm_kernel_oil_mt',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='soybeans',
            new_name='soybeans_mt',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='soybean_oil',
            new_name='soybean_oil_mt',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='soybean_meal',
            new_name='soybean_meal_mt',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='barley',
            new_name='barley_mt',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='maize',
            new_name='maize_mt',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='sorghum',
            new_name='sorghum_mt',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='rice_thai_5',
            new_name='rice_thai_5_mt',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='rice_thai_25',
            new_name='rice_thai_25_mt',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='rice_thai_a_1',
            new_name='rice_thai_a_1_mt',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='rice_vietnamese_5',
            new_name='rice_vietnamese_5_mt',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='wheat_us_srw',
            new_name='wheat_us_srw_mt',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='wheat_us_hrw',
            new_name='wheat_us_hrw_mt',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='banana_europe',
            new_name='banana_europe_kg',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='banana_us',
            new_name='banana_us_kg',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='orange',
            new_name='orange_kg',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='beef',
            new_name='beef_kg',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='chicken',
            new_name='chicken_kg',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='lamb',
            new_name='lamb_kg',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='shrimps_mexican',
            new_name='shrimps_mexican_kg',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='sugar_eu',
            new_name='sugar_eu_kg',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='sugar_us',
            new_name='sugar_us_kg',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='sugar_world',
            new_name='sugar_world_kg',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='tobacco_us_import_uv',
            new_name='tobacco_us_import_uv_mt',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='logs_cameroon',
            new_name='logs_cameroon_cubic_meter',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='logs_malaysian',
            new_name='logs_malaysian_cubic_meter',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='sawnwood_cameroon',
            new_name='sawnwood_cameroon_cubic_meter',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='sawnwood_malaysian',
            new_name='sawnwood_malaysian_cubic_meter',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='plywood',
            new_name='plywood_cents_sheet',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='cotton_a_index',
            new_name='cotton_a_index_kg',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='rubber_tsr20',
            new_name='rubber_tsr20_kg',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='rubber_rss3',
            new_name='rubber_rss3_kg',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='phosphate_rock',
            new_name='phosphate_rock_mt',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='dap',
            new_name='dap_mt',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='tsp',
            new_name='tsp_mt',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='urea',
            new_name='urea_mt',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='potassium_chloride',
            new_name='potassium_chloride_mt',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='aluminum',
            new_name='aluminum_mt',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='iron_ore_cfr_spot',
            new_name='iron_ore_cfr_spot_mt',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='copper',
            new_name='copper_mt',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='lead',
            new_name='lead_mt',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='tin',
            new_name='tin_mt',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='nickel',
            new_name='nickel_mt',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='zinc',
            new_name='zinc_mt',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='gold',
            new_name='gold_troy_oz',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='platinum',
            new_name='platinum_troy_oz',
        ),
        migrations.RenameField(
            model_name='commodity',
            old_name='silver',
            new_name='silver_troy_oz',
        ),
    ]